export enum StatutDemande {
  NOUVELLE = 'NOUVELLE',

  EN_ATTENTE_PIECES = 'EN_ATTENTE_PIECES',

  EN_VALIDATION = 'EN_VALIDATION',

  VALIDEE = 'VALIDEE',

  REJETEE = 'REJETEE',

  ANNULEE = 'ANNULEE',
}
