export enum StatutDemande {
  NOUVELLE = 'NOUVELLE',

  EN_ATTENTE_PIECES = 'EN_ATTENTE_PIECES',

  A_TRAITER = 'A_TRAITER',

  EN_COURS_TRAITEMENT = 'EN_COURS_TRAITEMENT',

  EN_ATTENTE_AVIS_MEDICAL = 'EN_ATTENTE_AVIS_MEDICAL',

  EN_ATTENTE_DECISION = 'EN_ATTENTE_DECISION',

  EN_ATTENTE_VALIDATION_DRH = 'EN_ATTENTE_VALIDATION_DRH',

  EN_ATTENTE_VALIDATION_INFIRMERIE = 'EN_ATTENTE_VALIDATION_INFIRMERIE',

  RETOURNEE = 'RETOURNEE',

  VALIDEE = 'VALIDEE',

  REJETEE = 'REJETEE',

  ANNULEE = 'ANNULEE',

  CLOTUREE = 'CLOTUREE',
}
