export enum StatutDemande {
  /** En cours de saisie : le dossier n'attend personne et peut encore être supprimé. */
  EN_SAISIE = 'EN_SAISIE',

  /** Soumis au contrôle RH : complétude du dossier et conformité des pièces. */
  EN_VERIFICATION_RH = 'EN_VERIFICATION_RH',

  NOUVELLE = 'NOUVELLE',

  EN_ATTENTE_PIECES = 'EN_ATTENTE_PIECES',

  A_TRAITER = 'A_TRAITER',

  EN_COURS_TRAITEMENT = 'EN_COURS_TRAITEMENT',

  EN_ATTENTE_AVIS_MEDICAL = 'EN_ATTENTE_AVIS_MEDICAL',

  EN_ATTENTE_DECISION = 'EN_ATTENTE_DECISION',

  EN_ATTENTE_VALIDATION_DRH = 'EN_ATTENTE_VALIDATION_DRH',

  EN_ATTENTE_VALIDATION_INFIRMERIE = 'EN_ATTENTE_VALIDATION_INFIRMERIE',

  RETOURNEE = 'RETOURNEE',

  VALIDEE = 'VALIDEE',

  REJETEE = 'REJETEE',

  ANNULEE = 'ANNULEE',

  CLOTUREE = 'CLOTUREE',
}
