export enum TypeSoin {
  CONSULTATIONS = 'CONSULTATIONS',

  EXAMENS_MEDICAUX = 'EXAMENS_MEDICAUX',

  INTERVENTION_CHIRURGICALE = 'INTERVENTION_CHIRURGICALE',

  HOSPITALISATION = 'HOSPITALISATION',
}
