export enum TypeNotification {
  NOUVELLE_TACHE = 'NOUVELLE_TACHE',

  NOUVELLE_DEMANDE = 'NOUVELLE_DEMANDE',

  DEMANDE_ASSIGNEE = 'DEMANDE_ASSIGNEE',

  DEMANDE_MODIFIEE = 'DEMANDE_MODIFIEE',

  ECHEANCE_PROCHE = 'ECHEANCE_PROCHE',

  DEMANDE_VALIDEE = 'DEMANDE_VALIDEE',

  DEMANDE_REJETEE = 'DEMANDE_REJETEE',

  INFORMATION = 'INFORMATION',
}
