package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AyantDroitAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAyantDroitAllPropertiesEquals(AyantDroit expected, AyantDroit actual) {
        assertAyantDroitAutoGeneratedPropertiesEquals(expected, actual);
        assertAyantDroitAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAyantDroitAllUpdatablePropertiesEquals(AyantDroit expected, AyantDroit actual) {
        assertAyantDroitUpdatableFieldsEquals(expected, actual);
        assertAyantDroitUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAyantDroitAutoGeneratedPropertiesEquals(AyantDroit expected, AyantDroit actual) {
        assertThat(actual)
            .as("Verify AyantDroit auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAyantDroitUpdatableFieldsEquals(AyantDroit expected, AyantDroit actual) {
        assertThat(actual)
            .as("Verify AyantDroit relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getPrenom()).as("check prenom").isEqualTo(expected.getPrenom()))
            .satisfies(a -> assertThat(a.getDateNaissance()).as("check dateNaissance").isEqualTo(expected.getDateNaissance()))
            .satisfies(a -> assertThat(a.getLien()).as("check lien").isEqualTo(expected.getLien()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAyantDroitUpdatableRelationshipsEquals(AyantDroit expected, AyantDroit actual) {
        assertThat(actual)
            .as("Verify AyantDroit relationships")
            .satisfies(a -> assertThat(a.getAgent()).as("check agent").isEqualTo(expected.getAgent()));
    }
}
