package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BoiteReceptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoiteReceptionAllPropertiesEquals(BoiteReception expected, BoiteReception actual) {
        assertBoiteReceptionAutoGeneratedPropertiesEquals(expected, actual);
        assertBoiteReceptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoiteReceptionAllUpdatablePropertiesEquals(BoiteReception expected, BoiteReception actual) {
        assertBoiteReceptionUpdatableFieldsEquals(expected, actual);
        assertBoiteReceptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoiteReceptionAutoGeneratedPropertiesEquals(BoiteReception expected, BoiteReception actual) {
        assertThat(actual)
            .as("Verify BoiteReception auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoiteReceptionUpdatableFieldsEquals(BoiteReception expected, BoiteReception actual) {
        assertThat(actual)
            .as("Verify BoiteReception relevant properties")
            .satisfies(a -> assertThat(a.getDateCreation()).as("check dateCreation").isEqualTo(expected.getDateCreation()))
            .satisfies(a ->
                assertThat(a.getDateDerniereLecture()).as("check dateDerniereLecture").isEqualTo(expected.getDateDerniereLecture())
            )
            .satisfies(a -> assertThat(a.getNombreNonLus()).as("check nombreNonLus").isEqualTo(expected.getNombreNonLus()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoiteReceptionUpdatableRelationshipsEquals(BoiteReception expected, BoiteReception actual) {
        // empty method
    }
}
