package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CarteBeneficiaireAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarteBeneficiaireAllPropertiesEquals(CarteBeneficiaire expected, CarteBeneficiaire actual) {
        assertCarteBeneficiaireAutoGeneratedPropertiesEquals(expected, actual);
        assertCarteBeneficiaireAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarteBeneficiaireAllUpdatablePropertiesEquals(CarteBeneficiaire expected, CarteBeneficiaire actual) {
        assertCarteBeneficiaireUpdatableFieldsEquals(expected, actual);
        assertCarteBeneficiaireUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarteBeneficiaireAutoGeneratedPropertiesEquals(CarteBeneficiaire expected, CarteBeneficiaire actual) {
        assertThat(actual)
            .as("Verify CarteBeneficiaire auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarteBeneficiaireUpdatableFieldsEquals(CarteBeneficiaire expected, CarteBeneficiaire actual) {
        assertThat(actual)
            .as("Verify CarteBeneficiaire relevant properties")
            .satisfies(a -> assertThat(a.getNumeroCarte()).as("check numeroCarte").isEqualTo(expected.getNumeroCarte()))
            .satisfies(a -> assertThat(a.getTypeBeneficiaire()).as("check typeBeneficiaire").isEqualTo(expected.getTypeBeneficiaire()))
            .satisfies(a -> assertThat(a.getDateDebutValidite()).as("check dateDebutValidite").isEqualTo(expected.getDateDebutValidite()))
            .satisfies(a -> assertThat(a.getDateFinValidite()).as("check dateFinValidite").isEqualTo(expected.getDateFinValidite()))
            .satisfies(a -> assertThat(a.getDateEmission()).as("check dateEmission").isEqualTo(expected.getDateEmission()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarteBeneficiaireUpdatableRelationshipsEquals(CarteBeneficiaire expected, CarteBeneficiaire actual) {
        assertThat(actual)
            .as("Verify CarteBeneficiaire relationships")
            .satisfies(a -> assertThat(a.getAgent()).as("check agent").isEqualTo(expected.getAgent()))
            .satisfies(a -> assertThat(a.getAyantDroit()).as("check ayantDroit").isEqualTo(expected.getAyantDroit()));
    }
}
