package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DemandePriseEnChargeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemandePriseEnChargeAllPropertiesEquals(DemandePriseEnCharge expected, DemandePriseEnCharge actual) {
        assertDemandePriseEnChargeAutoGeneratedPropertiesEquals(expected, actual);
        assertDemandePriseEnChargeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemandePriseEnChargeAllUpdatablePropertiesEquals(DemandePriseEnCharge expected, DemandePriseEnCharge actual) {
        assertDemandePriseEnChargeUpdatableFieldsEquals(expected, actual);
        assertDemandePriseEnChargeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemandePriseEnChargeAutoGeneratedPropertiesEquals(DemandePriseEnCharge expected, DemandePriseEnCharge actual) {
        assertThat(actual)
            .as("Verify DemandePriseEnCharge auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemandePriseEnChargeUpdatableFieldsEquals(DemandePriseEnCharge expected, DemandePriseEnCharge actual) {
        assertThat(actual)
            .as("Verify DemandePriseEnCharge relevant properties")
            .satisfies(a -> assertThat(a.getReference()).as("check reference").isEqualTo(expected.getReference()))
            .satisfies(a -> assertThat(a.getDateCreation()).as("check dateCreation").isEqualTo(expected.getDateCreation()))
            .satisfies(a -> assertThat(a.getDateModification()).as("check dateModification").isEqualTo(expected.getDateModification()))
            .satisfies(a -> assertThat(a.getTypeBeneficiaire()).as("check typeBeneficiaire").isEqualTo(expected.getTypeBeneficiaire()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getDateAssignation()).as("check dateAssignation").isEqualTo(expected.getDateAssignation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemandePriseEnChargeUpdatableRelationshipsEquals(DemandePriseEnCharge expected, DemandePriseEnCharge actual) {
        assertThat(actual)
            .as("Verify DemandePriseEnCharge relationships")
            .satisfies(a -> assertThat(a.getAgent()).as("check agent").isEqualTo(expected.getAgent()))
            .satisfies(a -> assertThat(a.getAyantDroit()).as("check ayantDroit").isEqualTo(expected.getAyantDroit()))
            .satisfies(a -> assertThat(a.getTypeSoin()).as("check typeSoin").isEqualTo(expected.getTypeSoin()))
            .satisfies(a ->
                assertThat(a.getEtablissementSante()).as("check etablissementSante").isEqualTo(expected.getEtablissementSante())
            );
    }
}
