package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DirectionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDirectionAllPropertiesEquals(Direction expected, Direction actual) {
        assertDirectionAutoGeneratedPropertiesEquals(expected, actual);
        assertDirectionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDirectionAllUpdatablePropertiesEquals(Direction expected, Direction actual) {
        assertDirectionUpdatableFieldsEquals(expected, actual);
        assertDirectionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDirectionAutoGeneratedPropertiesEquals(Direction expected, Direction actual) {
        assertThat(actual)
            .as("Verify Direction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDirectionUpdatableFieldsEquals(Direction expected, Direction actual) {
        assertThat(actual)
            .as("Verify Direction relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDirectionUpdatableRelationshipsEquals(Direction expected, Direction actual) {
        assertThat(actual)
            .as("Verify Direction relationships")
            .satisfies(a -> assertThat(a.getRegion()).as("check region").isEqualTo(expected.getRegion()));
    }
}
