package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GestionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGestionAllPropertiesEquals(Gestion expected, Gestion actual) {
        assertGestionAutoGeneratedPropertiesEquals(expected, actual);
        assertGestionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGestionAllUpdatablePropertiesEquals(Gestion expected, Gestion actual) {
        assertGestionUpdatableFieldsEquals(expected, actual);
        assertGestionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGestionAutoGeneratedPropertiesEquals(Gestion expected, Gestion actual) {
        assertThat(actual)
            .as("Verify Gestion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGestionUpdatableFieldsEquals(Gestion expected, Gestion actual) {
        assertThat(actual)
            .as("Verify Gestion relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGestionUpdatableRelationshipsEquals(Gestion expected, Gestion actual) {
        // empty method
    }
}
