package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HistoriqueActionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueActionAllPropertiesEquals(HistoriqueAction expected, HistoriqueAction actual) {
        assertHistoriqueActionAutoGeneratedPropertiesEquals(expected, actual);
        assertHistoriqueActionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueActionAllUpdatablePropertiesEquals(HistoriqueAction expected, HistoriqueAction actual) {
        assertHistoriqueActionUpdatableFieldsEquals(expected, actual);
        assertHistoriqueActionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueActionAutoGeneratedPropertiesEquals(HistoriqueAction expected, HistoriqueAction actual) {
        assertThat(actual)
            .as("Verify HistoriqueAction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueActionUpdatableFieldsEquals(HistoriqueAction expected, HistoriqueAction actual) {
        assertThat(actual)
            .as("Verify HistoriqueAction relevant properties")
            .satisfies(a -> assertThat(a.getAction()).as("check action").isEqualTo(expected.getAction()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getDateAction()).as("check dateAction").isEqualTo(expected.getDateAction()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueActionUpdatableRelationshipsEquals(HistoriqueAction expected, HistoriqueAction actual) {
        assertThat(actual)
            .as("Verify HistoriqueAction relationships")
            .satisfies(a -> assertThat(a.getDemande()).as("check demande").isEqualTo(expected.getDemande()));
    }
}
