package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PieceJustificativeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPieceJustificativeAllPropertiesEquals(PieceJustificative expected, PieceJustificative actual) {
        assertPieceJustificativeAutoGeneratedPropertiesEquals(expected, actual);
        assertPieceJustificativeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPieceJustificativeAllUpdatablePropertiesEquals(PieceJustificative expected, PieceJustificative actual) {
        assertPieceJustificativeUpdatableFieldsEquals(expected, actual);
        assertPieceJustificativeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPieceJustificativeAutoGeneratedPropertiesEquals(PieceJustificative expected, PieceJustificative actual) {
        assertThat(actual)
            .as("Verify PieceJustificative auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPieceJustificativeUpdatableFieldsEquals(PieceJustificative expected, PieceJustificative actual) {
        assertThat(actual)
            .as("Verify PieceJustificative relevant properties")
            .satisfies(a -> assertThat(a.getNomFichier()).as("check nomFichier").isEqualTo(expected.getNomFichier()))
            .satisfies(a -> assertThat(a.getCheminFichier()).as("check cheminFichier").isEqualTo(expected.getCheminFichier()))
            .satisfies(a -> assertThat(a.getDateAjout()).as("check dateAjout").isEqualTo(expected.getDateAjout()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPieceJustificativeUpdatableRelationshipsEquals(PieceJustificative expected, PieceJustificative actual) {
        assertThat(actual)
            .as("Verify PieceJustificative relationships")
            .satisfies(a -> assertThat(a.getDemande()).as("check demande").isEqualTo(expected.getDemande()));
    }
}
