package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TacheAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTacheAllPropertiesEquals(Tache expected, Tache actual) {
        assertTacheAutoGeneratedPropertiesEquals(expected, actual);
        assertTacheAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTacheAllUpdatablePropertiesEquals(Tache expected, Tache actual) {
        assertTacheUpdatableFieldsEquals(expected, actual);
        assertTacheUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTacheAutoGeneratedPropertiesEquals(Tache expected, Tache actual) {
        assertThat(actual)
            .as("Verify Tache auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTacheUpdatableFieldsEquals(Tache expected, Tache actual) {
        assertThat(actual)
            .as("Verify Tache relevant properties")
            .satisfies(a -> assertThat(a.getTitre()).as("check titre").isEqualTo(expected.getTitre()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getDateCreation()).as("check dateCreation").isEqualTo(expected.getDateCreation()))
            .satisfies(a -> assertThat(a.getDateAssignation()).as("check dateAssignation").isEqualTo(expected.getDateAssignation()))
            .satisfies(a -> assertThat(a.getDateEcheance()).as("check dateEcheance").isEqualTo(expected.getDateEcheance()))
            .satisfies(a -> assertThat(a.getDateTerminaison()).as("check dateTerminaison").isEqualTo(expected.getDateTerminaison()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getPriorite()).as("check priorite").isEqualTo(expected.getPriorite()))
            .satisfies(a -> assertThat(a.getLu()).as("check lu").isEqualTo(expected.getLu()))
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTacheUpdatableRelationshipsEquals(Tache expected, Tache actual) {
        assertThat(actual)
            .as("Verify Tache relationships")
            .satisfies(a -> assertThat(a.getDemande()).as("check demande").isEqualTo(expected.getDemande()))
            .satisfies(a -> assertThat(a.getBoiteReception()).as("check boiteReception").isEqualTo(expected.getBoiteReception()));
    }
}
